packages:
  # Essentials
  - ca-certificates
  - cmatrix
  - curl
  - fastfetch
  - fd-find
  - fuse-sshfs
  - fzf
  - gcc
  - git
  - git-delta
  - git-lfs
  - nodejs
  - openssl
  - ripgrep
  - stow
  - tree
  - unzip
  - wget
  - xclip
  - zoxide
  - zsh

  # Python
  - python3-libdnf5
  - python3-neovim
  - python3-pip
  - python-devel
  - uv

  # Docker engine
  - containerd.io
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin

  # Tools require configurations
  - bat
  - btop
  - kitty
  - lazygit
  - neovim
  - pet
  - tmux

  # Other GUI tools
  - 1password
  - firefox
