- name: Simulate stow
  shell:
    cmd: stow ghostty --simulate -v
    chdir: ~/.dotfiles/
  register: sim_result
  changed_when: False

- name: Stow dotfiles
  shell:
    cmd: stow ghostty
    chdir: ~/.dotfiles
  when: '"LINK: " in sim_result.stderr'

